// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsliO6lK85yftqbVR1WemEOl9Cp-VubUQ',
    appId: '1:835836104380:android:1ceeee9b2d9c7ee2d7cab9',
    messagingSenderId: '835836104380',
    projectId: 'jet-auth-v1',
    storageBucket: 'jet-auth-v1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADK_6ViK4V6NanmXMQRqhAL6hCGsoa2xw',
    appId: '1:835836104380:web:b1fc4df705071405d7cab9',
    messagingSenderId: '835836104380',
    projectId: 'jet-auth-v1',
    authDomain: 'jet-auth-v1.firebaseapp.com',
    storageBucket: 'jet-auth-v1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Wz2o3gW40w0LSHwQx17q9Qt3_YCKDEI',
    appId: '1:835836104380:ios:02ee4bef0b0fc0efd7cab9',
    messagingSenderId: '835836104380',
    projectId: 'jet-auth-v1',
    storageBucket: 'jet-auth-v1.firebasestorage.app',
    iosBundleId: 'com.example.flashAuth',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Wz2o3gW40w0LSHwQx17q9Qt3_YCKDEI',
    appId: '1:835836104380:ios:02ee4bef0b0fc0efd7cab9',
    messagingSenderId: '835836104380',
    projectId: 'jet-auth-v1',
    storageBucket: 'jet-auth-v1.firebasestorage.app',
    iosBundleId: 'com.example.flashAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADK_6ViK4V6NanmXMQRqhAL6hCGsoa2xw',
    appId: '1:835836104380:web:2cd825e55cba4522d7cab9',
    messagingSenderId: '835836104380',
    projectId: 'jet-auth-v1',
    authDomain: 'jet-auth-v1.firebaseapp.com',
    storageBucket: 'jet-auth-v1.firebasestorage.app',
  );

}