import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by 'flutterfire configure'
import 'screens/login_screen.dart';
import 'utils/theme.dart'; // Added

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const FlashAuthApp());
}

class FlashAuthApp extends StatelessWidget {
  const FlashAuthApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SilentMark',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme, // Applied Custom Theme
      home: const LoginScreen(),
    );
  }
}
